version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: YWiImBR2V5VbTF4z
    ports:
      - 27017:27017
    restart: unless-stopped 
    volumes:
      - mongodb:/opt/volumes/mongodb
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge